name: Website CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js environment with caching for npm dependencies
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies using npm
      - name: Install dependencies
        run: npm ci

      # Run tests (first because better)
      - name: Run tests
        run: npm test -- --watchAll=false

      # Build the React app (only runs if tests pass)
      - name: Build the app
        run: npm run build
